// Code generated by "go run -tags tools ./internal/cmd/dummy_visitor"; DO NOT EDIT.
package serde

func (vi BoolVisitor) String() string {
	return "bool"
}
func (vi BoolVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi BoolVisitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi BoolVisitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi BoolVisitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi BoolVisitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi BoolVisitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi BoolVisitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi BoolVisitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi BoolVisitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi BoolVisitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi BoolVisitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi BoolVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi BoolVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi BoolVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi BoolVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi BoolVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi BoolVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi BoolVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi BoolVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi ByteVisitor) String() string {
	return "byte"
}
func (vi ByteVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi ByteVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi ByteVisitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi ByteVisitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi ByteVisitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi ByteVisitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi ByteVisitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi ByteVisitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi ByteVisitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi ByteVisitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi ByteVisitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi ByteVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi ByteVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi ByteVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi ByteVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi ByteVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi ByteVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi ByteVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi ByteVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi BytesVisitor) String() string {
	return "bytes"
}
func (vi BytesVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi BytesVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi BytesVisitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi BytesVisitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi BytesVisitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi BytesVisitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi BytesVisitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi BytesVisitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi BytesVisitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi BytesVisitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi BytesVisitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi BytesVisitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi BytesVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi BytesVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi BytesVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi BytesVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi BytesVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi BytesVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi BytesVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Complex128Visitor) String() string {
	return "complex128"
}
func (vi Complex128Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Complex128Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Complex128Visitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi Complex128Visitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi Complex128Visitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi Complex128Visitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi Complex128Visitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi Complex128Visitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi Complex128Visitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi Complex128Visitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi Complex128Visitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi Complex128Visitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi Complex128Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Complex128Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Complex128Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Complex128Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Complex128Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Complex128Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Complex64Visitor) String() string {
	return "complex64"
}
func (vi Complex64Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Complex64Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Complex64Visitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi Complex64Visitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi Complex64Visitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi Complex64Visitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi Complex64Visitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi Complex64Visitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi Complex64Visitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi Complex64Visitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi Complex64Visitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi Complex64Visitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi Complex64Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Complex64Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Complex64Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Complex64Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Complex64Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Complex64Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi DummyVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi DummyVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi DummyVisitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi DummyVisitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi DummyVisitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi DummyVisitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi DummyVisitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi DummyVisitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi DummyVisitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi DummyVisitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi DummyVisitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi DummyVisitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi DummyVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi DummyVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi DummyVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi DummyVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi DummyVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi DummyVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi DummyVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi DummyVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Float32Visitor) String() string {
	return "float32"
}
func (vi Float32Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Float32Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Float32Visitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi Float32Visitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi Float32Visitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi Float32Visitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi Float32Visitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi Float32Visitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi Float32Visitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi Float32Visitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi Float32Visitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi Float32Visitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi Float32Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Float32Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Float32Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Float32Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Float32Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Float32Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Float64Visitor) String() string {
	return "float64"
}
func (vi Float64Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Float64Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Float64Visitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi Float64Visitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi Float64Visitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi Float64Visitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi Float64Visitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi Float64Visitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi Float64Visitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi Float64Visitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi Float64Visitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi Float64Visitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi Float64Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Float64Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Float64Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Float64Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Float64Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Float64Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Int16Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Int16Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Int16Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Int16Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Int16Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Int16Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Int16Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Int16Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Int16Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Int16Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Int32Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Int32Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Int32Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Int32Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Int32Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Int32Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Int32Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Int32Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Int32Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Int32Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Int64Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Int64Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Int64Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Int64Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Int64Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Int64Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Int64Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Int64Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Int64Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Int64Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Int8Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Int8Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Int8Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Int8Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Int8Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Int8Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Int8Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Int8Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Int8Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Int8Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi IntVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi IntVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi IntVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi IntVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi IntVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi IntVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi IntVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi IntVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi IntVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi IntVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi RuneVisitor) String() string {
	return "rune"
}
func (vi RuneVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi RuneVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi RuneVisitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi RuneVisitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi RuneVisitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi RuneVisitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi RuneVisitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi RuneVisitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi RuneVisitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi RuneVisitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi RuneVisitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi RuneVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi RuneVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi RuneVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi RuneVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi RuneVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi RuneVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi RuneVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi RuneVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi SkipVisitor) String() string {
	return "skip"
}
func (vi StringVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi StringVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi StringVisitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi StringVisitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi StringVisitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi StringVisitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi StringVisitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi StringVisitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi StringVisitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi StringVisitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi StringVisitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi StringVisitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi StringVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi StringVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi StringVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi StringVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi StringVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi StringVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Uint16Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Uint16Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Uint16Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Uint16Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Uint16Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Uint16Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Uint16Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Uint16Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Uint16Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Uint16Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Uint32Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Uint32Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Uint32Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Uint32Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Uint32Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Uint32Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Uint32Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Uint32Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Uint32Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Uint32Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Uint64Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Uint64Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Uint64Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Uint64Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Uint64Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Uint64Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Uint64Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Uint64Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Uint64Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Uint64Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Uint8Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Uint8Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Uint8Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Uint8Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Uint8Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Uint8Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Uint8Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Uint8Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Uint8Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Uint8Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi UintVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi UintVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi UintVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi UintVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi UintVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi UintVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi UintVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi UintVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi UintVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi UintVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
