// Code generated by internal/cmd/dummy_visitor; DO NOT EDIT.

package serde

func (vi DummyVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi DummyVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi DummyVisitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi DummyVisitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi DummyVisitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi DummyVisitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi DummyVisitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi DummyVisitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi DummyVisitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi DummyVisitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi DummyVisitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi DummyVisitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi DummyVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi DummyVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi DummyVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi DummyVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi DummyVisitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi DummyVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi DummyVisitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi DummyVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi DummyVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi DummyVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Int16Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Int16Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Int16Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Int16Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Int16Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Int16Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Int16Visitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi Int16Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Int16Visitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi Int16Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Int16Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Int16Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Int32Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Int32Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Int32Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Int32Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Int32Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Int32Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Int32Visitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi Int32Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Int32Visitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi Int32Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Int32Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Int32Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Int64Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Int64Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Int64Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Int64Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Int64Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Int64Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Int64Visitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi Int64Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Int64Visitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi Int64Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Int64Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Int64Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Int8Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Int8Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Int8Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Int8Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Int8Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Int8Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Int8Visitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi Int8Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Int8Visitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi Int8Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Int8Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Int8Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi IntVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi IntVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi IntVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi IntVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi IntVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi IntVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi IntVisitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi IntVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi IntVisitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi IntVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi IntVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi IntVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi StringVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi StringVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi StringVisitor) VisitInt(v int) (err error) {
	return NewInvalidTypeError(UnexpectedInt(v), vi)
}
func (vi StringVisitor) VisitInt8(v int8) (err error) {
	return NewInvalidTypeError(UnexpectedInt8(v), vi)
}
func (vi StringVisitor) VisitInt16(v int16) (err error) {
	return NewInvalidTypeError(UnexpectedInt16(v), vi)
}
func (vi StringVisitor) VisitInt32(v int32) (err error) {
	return NewInvalidTypeError(UnexpectedInt32(v), vi)
}
func (vi StringVisitor) VisitInt64(v int64) (err error) {
	return NewInvalidTypeError(UnexpectedInt64(v), vi)
}
func (vi StringVisitor) VisitUint(v uint) (err error) {
	return NewInvalidTypeError(UnexpectedUint(v), vi)
}
func (vi StringVisitor) VisitUint8(v uint8) (err error) {
	return NewInvalidTypeError(UnexpectedUint8(v), vi)
}
func (vi StringVisitor) VisitUint16(v uint16) (err error) {
	return NewInvalidTypeError(UnexpectedUint16(v), vi)
}
func (vi StringVisitor) VisitUint32(v uint32) (err error) {
	return NewInvalidTypeError(UnexpectedUint32(v), vi)
}
func (vi StringVisitor) VisitUint64(v uint64) (err error) {
	return NewInvalidTypeError(UnexpectedUint64(v), vi)
}
func (vi StringVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi StringVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi StringVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi StringVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi StringVisitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi StringVisitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi StringVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi StringVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Uint16Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Uint16Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Uint16Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Uint16Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Uint16Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Uint16Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Uint16Visitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi Uint16Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Uint16Visitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi Uint16Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Uint16Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Uint16Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Uint32Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Uint32Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Uint32Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Uint32Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Uint32Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Uint32Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Uint32Visitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi Uint32Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Uint32Visitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi Uint32Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Uint32Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Uint32Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Uint64Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Uint64Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Uint64Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Uint64Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Uint64Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Uint64Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Uint64Visitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi Uint64Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Uint64Visitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi Uint64Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Uint64Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Uint64Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi Uint8Visitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi Uint8Visitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi Uint8Visitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi Uint8Visitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi Uint8Visitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi Uint8Visitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi Uint8Visitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi Uint8Visitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi Uint8Visitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi Uint8Visitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi Uint8Visitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi Uint8Visitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
func (vi UintVisitor) VisitNil() (err error) {
	return NewInvalidTypeError(UnexpectedNil{}, vi)
}
func (vi UintVisitor) VisitBool(v bool) (err error) {
	return NewInvalidTypeError(UnexpectedBool(v), vi)
}
func (vi UintVisitor) VisitFloat32(v float32) (err error) {
	return NewInvalidTypeError(UnexpectedFloat32(v), vi)
}
func (vi UintVisitor) VisitFloat64(v float64) (err error) {
	return NewInvalidTypeError(UnexpectedFloat64(v), vi)
}
func (vi UintVisitor) VisitComplex64(v complex64) (err error) {
	return NewInvalidTypeError(UnexpectedComplex64(v), vi)
}
func (vi UintVisitor) VisitComplex128(v complex128) (err error) {
	return NewInvalidTypeError(UnexpectedComplex128(v), vi)
}
func (vi UintVisitor) VisitRune(v rune) (err error) {
	return NewInvalidTypeError(UnexpectedRune(v), vi)
}
func (vi UintVisitor) VisitString(v string) (err error) {
	return NewInvalidTypeError(UnexpectedString(v), vi)
}
func (vi UintVisitor) VisitByte(v byte) (err error) {
	return NewInvalidTypeError(UnexpectedByte(v), vi)
}
func (vi UintVisitor) VisitBytes(v []byte) (err error) {
	return NewInvalidTypeError(UnexpectedBytes{}, vi)
}
func (vi UintVisitor) VisitSlice(s SliceAccess) (err error) {
	return NewInvalidTypeError(UnexpectedSlice{}, vi)
}
func (vi UintVisitor) VisitMap(m MapAccess) (err error) {
	return NewInvalidTypeError(UnexpectedMap{}, vi)
}
